config/routes.rb
MyApp::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, :content, :presence => true
	validates :title, :content, :length => { :minimum => 5 }
	validates :title, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved"
		else
			render "new"
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(post_params)
			redirect_to posts_path, :notice => "Your post has been updated"
		else
			render "edit"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Successfully deleted"
	end

	private
		def post_params
			params.require(:post).permit(:title, :content, :updated_at, :created_at)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<ul>
		<li><%= value %></li>
	</ul>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>
	<p><%= f.submit "Update" %></p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog posts:</h1>
<p><%= link_to "Add New Post", new_post_path %></p>
<hr />

<% @posts.each do |p| %>
	<h2><%= link_to p.title, p %></h2>
	<p><%= p.content %></p>
	<p><%= link_to "Edit", edit_post_path(p) %> | 
	<%= link_to "Delete", p, :confirm => "Are you sure?", :method => :delete %>
	</p>

	<hr />
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
		<ul>
		<% @post.errors.full_messages.each do |message| %>
			<li class="Error"><p><%= message %></p></li>
		<% end %>
		</ul>
	<% end %>

	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :content %><br>
		<%= f.text_area :content %>
	</p>
	<p><%= f.submit "Add a new post" %></p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>
<small><%= @post.created_at %></small>
<br><br>
<%= link_to "Back", posts_path %>